// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MiniDumpProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("MiniDumpProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing MiniDumpProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MiniDumpProvider.Runtime"
    let [<Literal>] AssemblyProduct = "MiniDumpProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing MiniDumpProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
